### ISSUE TITLE
Due Date when creating new task

### ISSUE THREAD

**Issue by syncnj** [timdohm/de-crast#15]
Summary: This issues co-relates with issue #7 

Description:
In the browser version of Due Date: there's no prompt /guide to help the user select an exact due time.
Also, the recognization of the due date in the browser version sometimes produces an error (assign a random time in that day when only given a Date).
Suggestion: It would be helpful if there's a prompt /window for easy selection, like Android version.

Also, it seems that in the Android version, if the due date is within an hour ahead of the current time, it will categorize it as invalid deadline.  We think that as long as the due date is in the future (if it's very close to current time, a suggestion /confirmation might be helpful), but it should still be categorized as a valid deadline.

Severity: low.

**Comment by tsealex** [comment]
That's right, the current version only allows you to create a task due at least one hour later

**Comment by tsealex** [comment]
That's intended

**Comment by jerryand100** [comment]
The browser version is only intended for limited design testing, so that's why we didn't implement much time-picking support for browsers.

The current version of the code allows for any time greater than one minute into the future, and the time-picker defaults to the current time.

I also added the time requirement into the error message for an invalid deadline error.
